### ISSUE TITLE
Hey there?

### ISSUE THREAD

**Issue by ItsCEED** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#1]
Has anyone Manege to Compile the project as it should be?

Im running in a lot of troubles, even developers cant handle it...

Can anyone actually help me?

**Comment by HA6Bots** [comment]
Hey, I apologise for the messy nature of the bot. I never originally intended to release it to the public and therefore didn't really clean things up.
Here's some advice:

- First get the Server working. You will need a MySQL Database and Reddit API Keys for it (look at the config file). 
- Second get the Client working. This should be a fairly simple set up. Complete one video in it so that you can test the Video Generator 
- Third get the Video Generator working. You will need balabolka and the MLG Daniel Text to speech voice installed. Additionally you will also need youtube-upload and python27  if you would like to upload the videos automatically. If not, there are options to export the videos offline.

The config files should tell you all the dependencies it relies on (as well as the GitHub readme)
And yes there are people who were able to set up the bot and are currently using it with some success.

**Comment by ItsCEED** [comment]
> Hey, I apologise for the messy nature of the bot. I never originally intended to release it to the public and therefore didn't really clean things up.
> Here's some advice:
> 
> * First get the Server working. You will need a MySQL Database and Reddit API Keys for it (look at the config file).
> * Second get the Client working. This should be a fairly simple set up. Complete one video in it so that you can test the Video Generator
> * Third get the Video Generator working. You will need balabolka and the MLG Daniel Text to speech voice installed. Additionally you will also need youtube-upload and python27  if you would like to upload the videos automatically. If not, there are options to export the videos offline.
> 
> The config files should tell you all the dependencies it relies on (as well as the GitHub readme)
> And yes there are people who were able to set up the bot and are currently using it with some success.

Thank you! To be honest i didnt expect a reply!

I will give another try!

**Comment by HA6Bots** [comment]
MIT, do whatever you want with it.
