### ISSUE TITLE
How to clear the script buffer?

### ISSUE THREAD

**Issue by AjitbalaE** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#12]
Thanks for the script. Awesome work. 
I've ran into something. Can you please help me out on this one?
I've chosen a script and published a video. But I wasn't able to render it due to memory issues, so I would like to clear this from the queue. I've tried deleting the rawvideo.save file but it just keeps getting recreated as a part of the video generator script.
Would really appreciate your help!

**Comment by HA6Bots** [comment]
You need to change the script status from COMPLETE to something else. A script that is successfully rendered and uploaded/exported will have its script status set to SUCCESSUPLOAD which will tell the server to stop sending it to the generator, so since it is not rendering for you its status remains as COMPLETE. While a script has status COMPLETE it will always be sent to the video generator unless a rawvideo.save file has been created. 

So to fix, change the status of the script in something like MySQL Workbench and delete the rawsave file.
