### ISSUE TITLE
PLEASE GIVE FULL TUTORIAL ON HOW TO RUN

### ISSUE THREAD

**Issue by ManavMalhotra** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#56]
I am not able to understand what to do? I am an intermediate level python programmer. I am also getting error while installing cv2

**Comment by moistvl** [comment]
The process is pretty self-explanatory, when you look at the readme.md, code, and configuration files. It would be very difficult for someone to create a tutorial for it though because the setup will be specific to what you have available to you. For example, I'm running the MySQL server on separate server hardware from the Youtube Bot Server, which itself is running on a separate OS from the client, etc. (server running inside a WSL Ubuntu install, client running in Windows 10)

You would need to provide your exact hardware and specifications before someone could even begin to help you with a tutorial.
