### ISSUE TITLE
Error rendering/formatting videos

### ISSUE THREAD

**Issue by LuciferDeFallen** [HA6Bots/Automatic-Youtube-Reddit-Text-To-Speech-Video-Generator-and-Uploader#62]
Rendering clips goes alright but I get an error when the program starts formatting them.

![image](https://user-images.githubusercontent.com/53998864/109977712-6780da80-7cfd-11eb-9390-11a832e8bfcb.png)

I don't know what to do at this point, any help would be appreciated.

**Comment by alzeric** [comment]
I'm also getting this issue, if this doesn't get answered I'll try digging into it and seeing what's going on tomorrow.

**Comment by HA6Bots** [comment]
Can you try printing the error? Also does this occur for certain videos or all videos?

**Comment by LuciferDeFallen** [comment]
> Can you try printing the error? Also does this occur for certain videos or all videos?

I had this error every time I ran the video generator, Also, how do I print the error?

**Comment by alzeric** [comment]
For me I did a video that had and Estimated Length of 16m41s - ""Failed with an Index -883 is out of bounds for axis 0 with Size 0, Sorry, a error occured rending this video. Skipping it"

Second video I tried I just chose a few comments and video was only 3m20s and coverted just fine.

So not sure if it was an error due to size/length of video or just a random hiccup.  I'll try some longer videos again later tonight and let you know.

**Comment by alzeric** [comment]
Update: Maybe just a glitch in the matrix, just created a 12min video with no issues rendering...I'll at least call this one a rarity on my end, not sure about @LuciferDeFallen however.

**Comment by stratty7** [comment]
Yeah ran into this a bit a while ago, but changed to shorter videos and haven't run into it since. I don't normally run on askreddit videos and combine mulitple small topic videos into one. Think it has something to do with the number of clips in the video or something with the amount of text on screen at once or in one line. 

Do all of your renders fail? @LuciferDeFallen

**Comment by LuciferDeFallen** [comment]
I tried it on a 10min script and then a 2min script just now but it still fails after rendering. @stratty7

**Comment by LuciferDeFallen** [comment]
I renamed one of the transitions to 'standard.mp4', and it's working now, fun times.
